<a href="https://colab.research.google.com/github/beatricekiplagat/Week-4-Independent-Project/blob/main/Moringa_Data_Science_Prep_W4_Independent_Project_2021_05_Beatrice_Kiplagat_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Week 4 IP 
#We will import the libraries we need 
import pandas as pd
import numpy as np

In [13]:
# Creating the dataframe from a url to the csv file 
data_df = pd.read_csv("http://bit.ly/autolib_dataset",index_col = 0, dtype = {'year':str, 'month': str, 'day': str,'hour':str, 'minute': str} )
data_df

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
...                                  ...              ...  ...   ...     ...
8 avenue MÃ©nelotte                    2                2  ...    11      26
37 rue de Dantzig                      4                4  ...    16      56
142 rue du Bac                         1                1  ...     7       1
2 avenue du Val de Fontenay            2                2  ...    17      27
5 Rue Henry Brisson                    4                4  ...    10       2

[5000 rows x 24 columns]

In [14]:
#We will now count the number of non-missing values
data_df.count()

Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
Displayed comment       111
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Scheduled at             47
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
year                   5000
month                  5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

In [15]:
#We will now determine the no. of missing values in our dataset

data_df_missing= len(data_df) - data_df.count()
data_df_missing

Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [22]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 2 Avenue de Suffren to 5 Rue Henry Brisson
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cars                5000 non-null   int64
 1   Bluecar_counter     5000 non-null   int64
 2   Utilib_counter      5000 non-null   int64
 3   Utilib_1.4_counter  5000 non-null   int64
 4   Charge_slots        5000 non-null   int64
 5   Charging_status     5000 non-null   object
 6   City                5000 non-null   object
 7   ID                  5000 non-null   object
 8   Kind                5000 non-null   object
 9   Postal_code         5000 non-null   int64
 10  Rental_Status       5000 non-null   object
 11  Slots               5000 non-null   int64
 12  Station_type        5000 non-null   object
 13  Status              5000 non-null   object
 14  Year                5000 non-null   object
 15  Month               5000 non-null   object
 16  Day                 5000 non-null   object
 17  Hour                5000 non-null   object
 18  Minute              5000 non-null   object
dtypes: int64(7), object(12)
memory usage: 781.2+ KB

In [17]:
data_df.shape

(5000, 24)

In [18]:
#We will now drop duplicates 
data_df = data_df.drop_duplicates()
data_df

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
...                                  ...              ...  ...   ...     ...
8 avenue MÃ©nelotte                    2                2  ...    11      26
37 rue de Dantzig                      4                4  ...    16      56
142 rue du Bac                         1                1  ...     7       1
2 avenue du Val de Fontenay            2                2  ...    17      27
5 Rue Henry Brisson                    4                4  ...    10       2

[5000 rows x 24 columns]

In [19]:
#We will now standardize column names so we can remove unnecesary columns including the 2 with alot of null values
data_df.columns = map (str.lower,data_df.columns)
columns = ['Cars','Bluecar_counter','Utilib_counter','Utilib_1.4_counter','Charge_slots','Charging_status','City','Displayed_comment','ID','Kind','Geo_point','Postal_code', 'Public_Name','Rental_Status','Scheduled_at','Slots','Station_type','Status','Subscription_status','Year','Month','Day','Hour','Minute']
data_df.columns = columns

data_df.head(10)

                                    Cars  Bluecar_counter  ...  Hour  Minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
8 Boulevard Voltaire                   0                0  ...     7       2
37 rue Leblanc                         0                0  ...    18      20
17 Rue des Luaps ProlongÃ©e            3                3  ...    22      13
34 avenue Jean Moulin                  1                1  ...    22      58
41 boulevard de Rochechouart           6                6  ...    15       2

[10 rows x 24 columns]

In [20]:
#Removing unnecesary columns
data_df = data_df.drop(columns = ['Displayed_comment', 'Geo_point', 'Public_Name', 'Scheduled_at','Subscription_status'])
data_df

                                    Cars  Bluecar_counter  ...  Hour  Minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
...                                  ...              ...  ...   ...     ...
8 avenue MÃ©nelotte                    2                2  ...    11      26
37 rue de Dantzig                      4                4  ...    16      56
142 rue du Bac                         1                1  ...     7       1
2 avenue du Val de Fontenay            2                2  ...    17      27
5 Rue Henry Brisson                    4                4  ...    10       2

[5000 rows x 19 columns]

In [21]:
#We will check for null values again
data_df_missing= len(data_df) - data_df.count()
data_df_missing

Cars                  0
Bluecar_counter       0
Utilib_counter        0
Utilib_1.4_counter    0
Charge_slots          0
Charging_status       0
City                  0
ID                    0
Kind                  0
Postal_code           0
Rental_Status         0
Slots                 0
Station_type          0
Status                0
Year                  0
Month                 0
Day                   0
Hour                  0
Minute                0
dtype: int64

In [26]:
#We will now convert the last 4 into datetime then drop them
data_df['date'] = data_df.Year.str.cat([data_df.Month,data_df.Day],sep = '/')
data_df['time'] = data_df.Hour.str.cat([data_df.Minute],sep = ':')
data_df['date_time'] = data_df.date.str.cat([data_df.time],sep = ' ')
data_df = data_df.drop(columns = ['Year','Month','Day','Minute'])
data_df

                                    Cars  ...       date_time
Address                                   ...
2 Avenue de Suffren                    0  ...  2018/4/8 11:43
145 Rue Raymond Losserand              6  ...   2018/4/6 7:24
2 Avenue John Fitzgerald Kennedy       3  ...  2018/4/3 20:14
51 Rue EugÃ¨ne OudinÃ©                 3  ...   2018/4/4 4:37
6 avenue de la Porte de Champerret     3  ...  2018/4/8 17:23
...                                  ...  ...             ...
8 avenue MÃ©nelotte                    2  ...  2018/4/6 11:26
37 rue de Dantzig                      4  ...  2018/4/4 16:56
142 rue du Bac                         1  ...    2018/4/1 7:1
2 avenue du Val de Fontenay            2  ...  2018/4/4 17:27
5 Rue Henry Brisson                    4  ...   2018/4/8 10:2

[5000 rows x 18 columns]

In [34]:
# We will now only filter the values whose status is ok
data_df = data_df[data_df['Status'] == 'ok']
data_df

                                    Cars  ...       date_time
Address                                   ...
2 Avenue de Suffren                    0  ...  2018/4/8 11:43
145 Rue Raymond Losserand              6  ...   2018/4/6 7:24
2 Avenue John Fitzgerald Kennedy       3  ...  2018/4/3 20:14
51 Rue EugÃ¨ne OudinÃ©                 3  ...   2018/4/4 4:37
6 avenue de la Porte de Champerret     3  ...  2018/4/8 17:23
...                                  ...  ...             ...
8 avenue MÃ©nelotte                    2  ...  2018/4/6 11:26
37 rue de Dantzig                      4  ...  2018/4/4 16:56
142 rue du Bac                         1  ...    2018/4/1 7:1
2 avenue du Val de Fontenay            2  ...  2018/4/4 17:27
5 Rue Henry Brisson                    4  ...   2018/4/8 10:2

[4623 rows x 18 columns]

In [35]:
#We will check again for null values
data_df_missing= len(data_df) - data_df.count()
data_df_missing

Cars                  0
Bluecar_counter       0
Utilib_counter        0
Utilib_1.4_counter    0
Charge_slots          0
Charging_status       0
City                  0
ID                    0
Kind                  0
Postal_code           0
Rental_Status         0
Slots                 0
Station_type          0
Status                0
Hour                  0
date                  0
time                  0
date_time             0
dtype: int64

In [ ]:
#What is the most popular hour for returning cars?